[package]
name = "wave-tank"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
wasm-wave = "0.3.0"
wasmtime = "13.0.0"
wasmtime-wasi = "13.0.0"
wit-component = "0.14.4"
wit-parser = "0.11.3"
